defmodule AshMssql.Test.PrimaryKeyTest do
  @moduledoc false
  use AshMssql.RepoCase, async: false
  alias AshMssql.Test.{IntegerPost, Post, PostView, UuidV7Post}

  require Ash.Query

  describe "integer primary keys" do
    test "creates record with integer primary key" do
      assert %IntegerPost{} =
               IntegerPost
               |> Ash.Changeset.for_create(:create, %{title: "title"})
               |> Ash.create!()
    end

    test "the id is generated by the database and returned" do
      first = IntegerPost |> Ash.Changeset.for_create(:create, %{title: "one"}) |> Ash.create!()
      second = IntegerPost |> Ash.Changeset.for_create(:create, %{title: "two"}) |> Ash.create!()

      assert is_integer(first.id)
      assert is_integer(second.id)
      assert second.id > first.id
    end

    test "records can be fetched by their generated id" do
      post = IntegerPost |> Ash.Changeset.for_create(:create, %{title: "title"}) |> Ash.create!()

      assert Ash.get!(IntegerPost, post.id).title == "title"
    end
  end

  describe "uuid (v4) primary keys" do
    test "creates record with uuid primary key" do
      assert %Post{} =
               Post |> Ash.Changeset.for_create(:create, %{title: "title"}) |> Ash.create!()
    end

    test "the id is a generated version 4 uuid" do
      post = Post |> Ash.Changeset.for_create(:create, %{title: "title"}) |> Ash.create!()

      assert post.id =~ AshMssql.Test.UuidPatterns.v4()
    end

    test "records can be fetched by their generated id" do
      post = Post |> Ash.Changeset.for_create(:create, %{title: "title"}) |> Ash.create!()

      assert Ash.get!(Post, post.id).id == post.id

      assert [%Post{}] =
               Post
               |> Ash.Query.filter(id == ^post.id)
               |> Ash.read!()
    end
  end

  describe "uuid_v7 primary keys" do
    test "creates record with uuid_v7 primary key" do
      assert %UuidV7Post{} =
               UuidV7Post
               |> Ash.Changeset.for_create(:create, %{title: "title"})
               |> Ash.create!()
    end

    test "the id is a generated version 7 uuid" do
      post = UuidV7Post |> Ash.Changeset.for_create(:create, %{title: "title"}) |> Ash.create!()

      assert post.id =~ AshMssql.Test.UuidPatterns.v7()
    end

    test "records can be fetched by their generated id" do
      post = UuidV7Post |> Ash.Changeset.for_create(:create, %{title: "title"}) |> Ash.create!()

      assert Ash.get!(UuidV7Post, post.id).id == post.id

      assert [%UuidV7Post{}] =
               UuidV7Post
               |> Ash.Query.filter(id == ^post.id)
               |> Ash.read!()
    end
  end

  describe "resources without a primary key" do
    test "records can be created" do
      post =
        Post
        |> Ash.Changeset.for_action(:create, %{title: "not very interesting"})
        |> Ash.create!()

      assert {:ok, view} =
               PostView
               |> Ash.Changeset.for_action(:create, %{browser: :firefox, post_id: post.id})
               |> Ash.create()

      assert view.browser == :firefox
      assert view.post_id == post.id
      assert DateTime.diff(DateTime.utc_now(), view.time, :microsecond) < 1_000_000
    end

    test "records can be queried" do
      post =
        Post
        |> Ash.Changeset.for_action(:create, %{title: "not very interesting"})
        |> Ash.create!()

      expected =
        PostView
        |> Ash.Changeset.for_action(:create, %{browser: :firefox, post_id: post.id})
        |> Ash.create!()

      assert {:ok, [actual]} = Ash.read(PostView)

      assert actual.time == expected.time
      assert actual.browser == expected.browser
      assert actual.post_id == expected.post_id
    end
  end
end
