defmodule AshMssql.DataLayer do
  @index %Spark.Dsl.Entity{
    name: :index,
    describe: """
    Add an index to be managed by the migration generator.
    """,
    examples: [
      "index [\"column\", \"column2\"], unique: true, where: \"thing = TRUE\""
    ],
    target: AshMssql.CustomIndex,
    schema: AshMssql.CustomIndex.schema(),
    transform: {AshMssql.CustomIndex, :transform, []},
    args: [:fields]
  }

  @custom_indexes %Spark.Dsl.Section{
    name: :custom_indexes,
    describe: """
    A section for configuring indexes to be created by the migration generator.

    In general, prefer to use `identities` for simple unique constraints. This is a tool to allow
    for declaring more complex indexes.
    """,
    examples: [
      """
      custom_indexes do
        index [:column1, :column2], unique: true, where: "thing = TRUE"
      end
      """
    ],
    entities: [
      @index
    ]
  }

  @statement %Spark.Dsl.Entity{
    name: :statement,
    describe: """
    Add a custom statement for migrations.
    """,
    examples: [
      """
      statement :pgweb_idx do
        up "CREATE INDEX pgweb_idx ON pgweb USING GIN (to_tsvector('english', title || ' ' || body));"
        down "DROP INDEX pgweb_idx;"
      end
      """
    ],
    target: AshMssql.Statement,
    schema: AshMssql.Statement.schema(),
    args: [:name]
  }

  @custom_statements %Spark.Dsl.Section{
    name: :custom_statements,
    describe: """
    A section for configuring custom statements to be added to migrations.

    Changing custom statements may require manual intervention, because Ash can't determine what order they should run
    in (i.e if they depend on table structure that you've added, or vice versa). As such, any `down` statements we run
    for custom statements happen first, and any `up` statements happen last.

    Additionally, when changing a custom statement, we must make some assumptions, i.e that we should migrate
    the old structure down using the previously configured `down` and recreate it.

    This may not be desired, and so what you may end up doing is simply modifying the old migration and deleting whatever was
    generated by the migration generator. As always: read your migrations after generating them!
    """,
    examples: [
      """
      custom_statements do
        # the name is used to detect if you remove or modify the statement
        statement :pgweb_idx do
          up "CREATE INDEX pgweb_idx ON pgweb USING GIN (to_tsvector('english', title || ' ' || body));"
          down "DROP INDEX pgweb_idx;"
        end
      end
      """
    ],
    entities: [
      @statement
    ]
  }

  @reference %Spark.Dsl.Entity{
    name: :reference,
    describe: """
    Configures the reference for a relationship in resource migrations.

    Keep in mind that multiple relationships can theoretically involve the same destination and foreign keys.
    In those cases, you only need to configure the `reference` behavior for one of them. Any conflicts will result
    in an error, across this resource and any other resources that share a table with this one. For this reason,
    instead of adding a reference configuration for `:nothing`, its best to just leave the configuration out, as that
    is the default behavior if *no* relationship anywhere has configured the behavior of that reference.
    """,
    examples: [
      "reference :post, on_delete: :delete, on_update: :update, name: \"comments_to_posts_fkey\""
    ],
    args: [:relationship],
    target: AshMssql.Reference,
    schema: AshMssql.Reference.schema()
  }

  @references %Spark.Dsl.Section{
    name: :references,
    describe: """
    A section for configuring the references (foreign keys) in resource migrations.

    This section is only relevant if you are using the migration generator with this resource.
    Otherwise, it has no effect.
    """,
    examples: [
      """
      references do
        reference :post, on_delete: :delete, on_update: :update, name: "comments_to_posts_fkey"
      end
      """
    ],
    entities: [@reference],
    schema: [
      polymorphic_on_delete: [
        type: {:one_of, [:delete, :nilify, :nothing, :restrict]},
        doc:
          "For polymorphic resources, configures the on_delete behavior of the automatically generated foreign keys to source tables."
      ],
      polymorphic_on_update: [
        type: {:one_of, [:update, :nilify, :nothing, :restrict]},
        doc:
          "For polymorphic resources, configures the on_update behavior of the automatically generated foreign keys to source tables."
      ],
      polymorphic_name: [
        type: {:one_of, [:update, :nilify, :nothing, :restrict]},
        doc:
          "For polymorphic resources, configures the on_update behavior of the automatically generated foreign keys to source tables."
      ]
    ]
  }

  @references %Spark.Dsl.Section{
    name: :references,
    describe: """
    A section for configuring the references (foreign keys) in resource migrations.

    This section is only relevant if you are using the migration generator with this resource.
    Otherwise, it has no effect.
    """,
    examples: [
      """
      references do
        reference :post, on_delete: :delete, on_update: :update, name: "comments_to_posts_fkey"
      end
      """
    ],
    entities: [@reference],
    schema: [
      polymorphic_on_delete: [
        type: {:one_of, [:delete, :nilify, :nothing, :restrict]},
        doc:
          "For polymorphic resources, configures the on_delete behavior of the automatically generated foreign keys to source tables."
      ],
      polymorphic_on_update: [
        type: {:one_of, [:update, :nilify, :nothing, :restrict]},
        doc:
          "For polymorphic resources, configures the on_update behavior of the automatically generated foreign keys to source tables."
      ],
      polymorphic_name: [
        type: {:one_of, [:update, :nilify, :nothing, :restrict]},
        doc:
          "For polymorphic resources, configures the on_update behavior of the automatically generated foreign keys to source tables."
      ]
    ]
  }

  @mssql %Spark.Dsl.Section{
    name: :mssql,
    describe: """
    MSSQL data layer configuration
    """,
    sections: [
      @custom_indexes,
      @custom_statements,
      @references
    ],
    modules: [
      :repo
    ],
    examples: [
      """
      mssql do
        repo MyApp.Repo
        table "organizations"
      end
      """
    ],
    schema: [
      repo: [
        type: {:or, [{:behaviour, Ecto.Repo}, {:fun, 2}]},
        required: true,
        doc:
          "The repo that will be used to fetch your data. See the `AshMssql.Repo` documentation for more. Can also be a function that takes a resource and a type (`:read | :mutate`) and returns the repo, e.g. to route reads to a replica."
      ],
      migrate?: [
        type: :boolean,
        default: true,
        doc:
          "Whether or not to include this resource in the generated migrations with `mix ash.generate_migrations`"
      ],
      migration_types: [
        type: :keyword_list,
        default: [],
        doc:
          "A keyword list of attribute names to the ecto migration type that should be used for that attribute. Only necessary if you need to override the defaults."
      ],
      migration_defaults: [
        type: :keyword_list,
        default: [],
        doc: """
        A keyword list of attribute names to the ecto migration default that should be used for that attribute. The string you use will be placed verbatim in the migration. Use fragments like `fragment(\\\\"now()\\\\")`, or for `nil`, use `\\\\"nil\\\\"`.
        """
      ],
      base_filter_sql: [
        type: :string,
        doc:
          "A raw sql version of the base_filter, e.g `representative = true`. Required if trying to create a unique constraint on a resource with a base_filter"
      ],
      skip_unique_indexes: [
        type: {:wrap_list, :atom},
        default: false,
        doc: "Skip generating unique indexes when generating migrations"
      ],
      unique_index_names: [
        type:
          {:list,
           {:or,
            [{:tuple, [{:list, :atom}, :string]}, {:tuple, [{:list, :atom}, :string, :string]}]}},
        default: [],
        doc: """
        A list of unique index names that could raise errors that are not configured in identities, or an mfa to a function that takes a changeset and returns the list. In the format `{[:affected, :keys], "name_of_constraint"}` or `{[:affected, :keys], "name_of_constraint", "custom error message"}`
        """
      ],
      exclusion_constraint_names: [
        type: :any,
        default: [],
        doc: """
        A list of exclusion constraint names that could raise errors. Must be in the format `{:affected_key, "name_of_constraint"}` or `{:affected_key, "name_of_constraint", "custom error message"}`
        """
      ],
      identity_index_names: [
        type: :any,
        default: [],
        doc: """
        A keyword list of identity names to the unique index name that they should use when being managed by the migration generator.
        """
      ],
      foreign_key_names: [
        type: {:list, {:or, [{:tuple, [:atom, :string]}, {:tuple, [:string, :string]}]}},
        default: [],
        doc: """
        A list of foreign keys that could raise errors, or an mfa to a function that takes a changeset and returns a list. In the format: `{:key, "name_of_constraint"}` or `{:key, "name_of_constraint", "custom error message"}`
        """
      ],
      migration_ignore_attributes: [
        type: {:list, :atom},
        default: [],
        doc: """
        A list of attributes that will be ignored when generating migrations.
        """
      ],
      table: [
        type: :string,
        doc: """
        The table to store and read the resource from. If this is changed, the migration generator will not remove the old table.
        """
      ],
      polymorphic?: [
        type: :boolean,
        default: false,
        doc: """
        Declares this resource as polymorphic. See the [polymorphic resources guide](/documentation/topics/resources/polymorphic-resources.md) for more.
        """
      ]
    ]
  }

  @behaviour Ash.DataLayer

  @sections [@mssql]

  @moduledoc """
  A mssql data layer that leverages Ecto's mssql capabilities.
  """

  use Spark.Dsl.Extension,
    sections: @sections,
    transformers: [
      AshMssql.Transformers.VerifyRepo,
      AshMssql.Transformers.EnsureTableOrPolymorphic
    ],
    verifiers: [
      AshMssql.Transformers.ValidateReferences
    ]

  def migrate(args) do
    # TODO: take args that we care about
    Mix.Task.run("ash_mssql.migrate", args)
  end

  def rollback(args) do
    repos = AshMssql.Mix.Helpers.repos!([], args)

    show_for_repo? = Enum.count_until(repos, 2) == 2

    for repo <- repos do
      for_repo =
        if show_for_repo? do
          " for repo #{inspect(repo)}"
        else
          ""
        end

      migrations_path = AshMssql.Mix.Helpers.migrations_path([], repo)

      files =
        migrations_path
        |> Path.join("**/*.exs")
        |> Path.wildcard()
        |> Enum.sort()
        |> Enum.reverse()
        |> Enum.take(20)
        |> Enum.map(&String.trim_leading(&1, migrations_path))
        |> Enum.with_index()
        |> Enum.map(fn {file, index} -> "#{index + 1}: #{file}" end)

      n =
        Mix.shell().prompt(
          """
          How many migrations should be rolled back#{for_repo}? (default: 0)

          Last 20 migration names, with the input you must provide to
          rollback up to *and including* that migration:

          #{Enum.join(files, "\n")}
          Rollback to:
          """
          |> String.trim_trailing()
        )
        |> String.trim()
        |> case do
          "" ->
            0

          n ->
            try do
              String.to_integer(n)
            rescue
              _ ->
                # credo:disable-for-next-line
                raise "Required an integer value, got: #{n}"
            end
        end

      Mix.Task.run("ash_mssql.rollback", args ++ ["-r", inspect(repo), "-n", to_string(n)])
      Mix.Task.reenable("ash_mssql.rollback")
    end
  end

  def codegen(args) do
    # TODO: take args that we care about
    Mix.Task.run("ash_mssql.generate_migrations", args)
  end

  def setup(args) do
    # TODO: take args that we care about
    Mix.Task.run("ash_mssql.create", args)
    Mix.Task.run("ash_mssql.migrate", args)
  end

  def tear_down(args) do
    # TODO: take args that we care about
    Mix.Task.run("ash_mssql.drop", args)
  end

  import Ecto.Query, only: [from: 2, subquery: 1]

  @impl true
  def can?(_, :async_engine), do: false
  def can?(_, :bulk_create), do: true
  def can?(_, {:lock, _}), do: false

  def can?(_, :transact), do: true
  def can?(_, :composite_primary_key), do: true
  def can?(_, {:atomic, :update}), do: true
  def can?(_, {:atomic, :upsert}), do: true
  def can?(_, :upsert), do: true
  def can?(_, :changeset_filter), do: true

  def can?(resource, {:join, other_resource}) do
    data_layer = Ash.DataLayer.data_layer(resource)
    other_data_layer = Ash.DataLayer.data_layer(other_resource)

    data_layer == other_data_layer and
      AshMssql.DataLayer.Info.repo(resource) == AshMssql.DataLayer.Info.repo(other_resource)
  end

  def can?(_resource, {:lateral_join, _}) do
    false
  end

  def can?(_, :boolean_filter), do: true

  def can?(_, {:aggregate, _type}), do: false

  def can?(_, :aggregate_filter), do: false
  def can?(_, :aggregate_sort), do: false
  def can?(_, :expression_calculation), do: true
  def can?(_, :expression_calculation_sort), do: true
  def can?(_, :create), do: true
  def can?(_, :select), do: true
  def can?(_, :action_select), do: true
  def can?(_, :read), do: true

  def can?(resource, action) when action in ~w[update destroy]a do
    resource
    |> Ash.Resource.Info.primary_key()
    |> Enum.any?()
  end

  def can?(_, :filter), do: true
  def can?(_, :limit), do: true
  def can?(_, :offset), do: true
  def can?(_, :multitenancy), do: false

  def can?(_, {:filter_relationship, %{manual: {module, _}}}) do
    Spark.implements_behaviour?(module, AshMssql.ManualRelationship)
  end

  def can?(_, {:filter_relationship, _}), do: true

  def can?(_, {:aggregate_relationship, _}), do: false

  def can?(_, :timeout), do: true
  def can?(_, {:filter_expr, %Ash.Query.Function.StringJoin{}}), do: false
  # SQL Server has no array type; STRING_SPLIT returns rows, not a value
  def can?(_, {:filter_expr, %Ash.Query.Function.StringSplit{}}), do: false
  def can?(_, {:filter_expr, _}), do: true
  def can?(_, :nested_expressions), do: true
  def can?(_, {:query_aggregate, _}), do: true
  def can?(_, :sort), do: true
  def can?(_, :distinct_sort), do: false
  def can?(_, :distinct), do: false
  def can?(_, {:sort, _}), do: true
  def can?(_, _), do: false

  if Code.ensure_loaded?(Igniter) do
    def install(igniter, module, Ash.Resource, _path, argv) do
      table_name =
        module
        |> Module.split()
        |> List.last()
        |> Macro.underscore()
        |> Igniter.Inflex.pluralize()

      {options, _, _} = OptionParser.parse(argv, switches: [repo: :string])

      repo =
        case options[:repo] do
          nil ->
            Igniter.Project.Module.module_name(igniter, "Repo")

          repo ->
            Igniter.Project.Module.parse(repo)
        end

      igniter
      |> Spark.Igniter.set_option(module, [:mssql, :table], table_name)
      |> Spark.Igniter.set_option(module, [:mssql, :repo], repo)
    end

    def install(igniter, _, _, _), do: igniter
  end

  @impl true
  def limit(query, nil, _), do: {:ok, query}

  def limit(query, limit, _resource) do
    {:ok, from(row in query, limit: ^limit)}
  end

  @impl true
  def source(resource) do
    AshMssql.DataLayer.Info.table(resource) || ""
  end

  @impl true
  def set_context(resource, data_layer_query, context) do
    start_bindings = context[:data_layer][:start_bindings_at] || 0
    data_layer_query = from(row in data_layer_query, as: ^start_bindings)

    data_layer_query =
      if context[:data_layer][:table] do
        %{
          data_layer_query
          | from: %{data_layer_query.from | source: {context[:data_layer][:table], resource}}
        }
      else
        data_layer_query
      end

    {:ok,
     AshSql.Bindings.default_bindings(
       data_layer_query,
       resource,
       AshMssql.SqlImplementation,
       context
     )}
  end

  @impl true
  def offset(query, nil, _), do: query

  def offset(%{offset: old_offset} = query, 0, _resource) when old_offset in [0, nil] do
    {:ok, query}
  end

  def offset(query, offset, _resource) do
    {:ok, from(row in query, offset: ^offset)}
  end

  @impl true
  def run_aggregate_query(query, aggregates, resource) do
    {exists, aggregates} = Enum.split_with(aggregates, &(&1.kind == :exists))
    query = AshSql.Bindings.default_bindings(query, resource, AshMssql.SqlImplementation)

    query =
      if query.limit do
        query =
          query
          |> Ecto.Query.exclude(:select)
          |> Ecto.Query.exclude(:order_by)
          |> Map.put(:windows, [])

        from(row in subquery(query), as: ^0, select: %{})
      else
        query
        |> Ecto.Query.exclude(:select)
        |> Ecto.Query.exclude(:order_by)
        |> Map.put(:windows, [])
        |> Ecto.Query.select(%{})
      end

    query_before_select = query

    query =
      Enum.reduce(
        aggregates,
        query,
        fn agg, query ->
          AshSql.Aggregate.add_subquery_aggregate_select(
            query,
            agg.relationship_path |> Enum.drop(1),
            agg,
            resource,
            true,
            Ash.Resource.Info.relationship(resource, agg.relationship_path |> Enum.at(1))
          )
        end
      )

    result =
      case aggregates do
        [] ->
          %{}

        _ ->
          dynamic_repo(resource, query, :read).one(query, repo_opts(nil, nil, resource))
      end

    {:ok, add_exists_aggs(result, resource, query_before_select, exists)}
  end

  defp add_exists_aggs(result, resource, query, exists) do
    repo = dynamic_repo(resource, query, :read)
    repo_opts = repo_opts(nil, nil, resource)

    Enum.reduce(exists, result, fn agg, result ->
      {:ok, filtered} =
        case agg do
          %{query: %{filter: filter}} when not is_nil(filter) ->
            filter(query, filter, resource)

          _ ->
            {:ok, query}
        end

      Map.put(
        result || %{},
        agg.name,
        repo.exists?(filtered, repo_opts)
      )
    end)
  end

  @impl true
  def run_query(query, resource) do
    with_sort_applied =
      if query.__ash_bindings__[:sort_applied?] do
        {:ok, query}
      else
        AshSql.Sort.apply_sort(query, query.__ash_bindings__[:sort], resource)
      end

    case with_sort_applied do
      {:error, error} ->
        {:error, error}

      {:ok, query} ->
        query =
          if query.__ash_bindings__[:__order__?] && query.windows[:order] do
            order_by = %{query.windows[:order] | expr: query.windows[:order].expr[:order_by]}

            %{
              query
              | windows: Keyword.delete(query.windows, :order),
                order_bys: [order_by]
            }
          else
            %{query | windows: Keyword.delete(query.windows, :order)}
          end

        if AshMssql.DataLayer.Info.polymorphic?(resource) && no_table?(query) do
          raise_table_error!(resource, :read)
        else
          primary_key = Ash.Resource.Info.primary_key(resource)

          {:ok,
           dynamic_repo(resource, query, :read).all(query, repo_opts(nil, nil, resource))
           |> Enum.uniq_by(&Map.take(&1, primary_key))}
        end
    end
  rescue
    e ->
      handle_raised_error(e, __STACKTRACE__, query, resource)
  end

  defp no_table?(%{from: %{source: {"", _}}}), do: true
  defp no_table?(_), do: false

  # The tenant is accepted (Ash passes it through for every multitenancy
  # strategy, and for plain resources when set explicitly) but adds no repo
  # options: attribute-strategy multitenancy filters at the query layer, and
  # context (schema-prefix) multitenancy is not supported by this data layer
  # (`can?(:multitenancy)` is false, so ash rejects `strategy :context` at
  # compile time). If that capability is ever enabled, this must return
  # `[prefix: tenant]` for context strategy — and destroy/2 plus the read
  # paths must start passing their tenant through as well.
  defp repo_opts(timeout, _tenant, _resource) do
    add_timeout([], timeout)
  end

  defp repo_opts(timeout, _resource) do
    add_timeout([], timeout)
  end

  defp add_timeout(opts, timeout) when not is_nil(timeout) do
    Keyword.put(opts, :timeout, timeout)
  end

  defp add_timeout(opts, _), do: opts

  @impl true
  def functions(_resource) do
    [
      AshMssql.Functions.Like,
      AshMssql.Functions.ILike
    ]
  end

  @impl true
  def resource_to_query(resource, _) do
    from(row in {AshMssql.DataLayer.Info.table(resource) || "", resource}, [])
  end

  @impl true
  def bulk_create(resource, stream, options) do
    changesets = Enum.to_list(stream)

    repo = dynamic_repo(resource, Enum.at(changesets, 0))

    opts = repo_opts(nil, options[:tenant], resource)

    source = resolve_source(resource, Enum.at(changesets, 0))

    try do
      # opts =
      #   if options[:upsert?] do
      #     # Ash groups changesets by atomics before dispatching them to the data layer
      #     # this means that all changesets have the same atomics
      #     %{atomics: atomics, filter: filter} = Enum.at(changesets, 0)

      #     query = from(row in resource, as: ^0)

      #     query =
      #       query
      #       |> AshSql.Bindings.default_bindings(resource, AshMssql.SqlImplementation)

      #     upsert_set =
      #       upsert_set(resource, changesets, options)

      #     on_conflict =
      #       case AshSql.Atomics.query_with_atomics(
      #              resource,
      #              query,
      #              filter,
      #              atomics,
      #              %{},
      #              upsert_set
      #            ) do
      #         :empty ->
      #           :nothing

      #         {:ok, query} ->
      #           query

      #         {:error, error} ->
      #           raise Ash.Error.to_ash_error(error)
      #       end

      #     opts
      #     |> Keyword.put(:on_conflict, on_conflict)
      #     |> Keyword.put(
      #       :conflict_target,
      #       conflict_target(
      #         resource,
      #         options[:upsert_keys] || Ash.Resource.Info.primary_key(resource)
      #       )
      #     )
      #   else
      #     opts
      #   end

      opts =
        if schema = Enum.at(changesets, 0).context[:data_layer][:schema] do
          Keyword.put(opts, :prefix, schema)
        else
          opts
        end

      ecto_changesets = Enum.map(changesets, & &1.attributes)
      resource_for_returning = if options.return_records?, do: resource, else: nil

      # Returned rows are matched back to their changesets by primary key
      # (`align_results_with_changesets/3`) — and by the upsert keys for
      # upserts — so those must stay selected regardless of what the action
      # asks for.
      action_select =
        case action_select_with_required(options[:action_select], resource) do
          nil ->
            nil

          fields ->
            fields
            |> Enum.concat(if options[:upsert?], do: options[:upsert_keys] || [], else: [])
            |> Enum.uniq()
        end

      result =
        if options[:upsert?] do
          upsert_all_returning(
            source,
            resource,
            ecto_changesets,
            options,
            action_select,
            repo,
            opts
          )
        else
          insert_all_returning(
            source,
            ecto_changesets,
            repo,
            resource_for_returning,
            action_select,
            opts
          )
        end

      case result do
        {_, nil} ->
          :ok

        {_, results} ->
          if options[:single?] do
            {:ok, results}
          else
            # MSSQL does not guarantee that OUTPUT rows come back in VALUES
            # order, so returned records must be matched back to their
            # changesets by primary key (client-supplied, e.g. uuid pkeys)
            # rather than positionally. Falls back to positional zip only when
            # pkey values weren't supplied (e.g. server-generated identities).
            results = align_results_with_changesets(results, changesets, resource)

            {:ok,
             Stream.zip_with(results, changesets, fn result, changeset ->
               Ash.Resource.put_metadata(
                 result,
                 :bulk_create_index,
                 changeset.context.bulk_create.index
               )
             end)}
          end
      end
    rescue
      e ->
        changeset = Ash.Changeset.new(resource)

        handle_raised_error(
          e,
          __STACKTRACE__,
          {:bulk_create, ecto_changeset(changeset.data, changeset, :create, false)},
          resource
        )
    end
  end

  # Reorder OUTPUT-returned records to match changeset order by primary key.
  # Only possible when every changeset carries a full primary key (the common
  # case: client-generated uuid keys); otherwise returns results as-is.
  defp align_results_with_changesets(results, changesets, resource) do
    pkey = Ash.Resource.Info.primary_key(resource)

    changeset_keys =
      Enum.map(changesets, fn changeset ->
        Enum.map(pkey, &Map.get(changeset.attributes, &1))
      end)

    if Enum.any?(changeset_keys, fn key -> Enum.any?(key, &is_nil/1) end) do
      results
    else
      by_key = Map.new(results, fn record -> {Enum.map(pkey, &Map.get(record, &1)), record} end)

      aligned = Enum.map(changeset_keys, &Map.get(by_key, &1))

      if Enum.any?(aligned, &is_nil/1) do
        # A key didn't match (type dump mismatch etc.) — fall back to the raw
        # order rather than dropping records.
        results
      else
        aligned
      end
    end
  end

  defp insert_all_returning(source, entries, repo, nil, _action_select, opts) do
    repo.insert_all(source, entries, opts)
  end

  defp insert_all_returning(source, entries, repo, resource, action_select, opts) do
    # MSSQL supports the OUTPUT clause (the RETURNING-equivalent), which Ecto's
    # Tds adapter exposes via `:returning`. This gives Postgres-parity batch
    # inserts that return the inserted rows directly — including server-generated
    # identity/uuid keys — instead of a fragile SCOPE_IDENTITY()/reload round-trip
    # (SCOPE_IDENTITY() is batch-scoped and would be NULL on a separate query).
    opts = Keyword.put(opts, :returning, action_select || true)

    if length(entries) > 1 and not alignable_by_pkey?(entries, resource) do
      # OUTPUT rows are not guaranteed to come back in VALUES order, and
      # without client-supplied primary keys (identity or database-generated
      # uuid pks) the rows can't be matched back to their changesets
      # afterwards. Insert row by row so each OUTPUT row is unambiguously its
      # entry's record.
      {count, records} =
        Enum.reduce(entries, {0, []}, fn entry, {count, acc} ->
          case repo.insert_all(source, [entry], opts) do
            {n, [record]} -> {count + n, [record | acc]}
            {n, _} -> {count + n, acc}
          end
        end)

      {count, Enum.reverse(records)}
    else
      repo.insert_all(source, entries, opts)
    end
  end

  defp alignable_by_pkey?(entries, resource) do
    pkey = Ash.Resource.Info.primary_key(resource)

    Enum.all?(entries, fn entry ->
      Enum.all?(pkey, &(not is_nil(Map.get(entry, &1))))
    end)
  end

  # Ecto's Tds adapter only supports `on_conflict: :raise`, so upsert cannot go
  # through `insert_all/3`. Instead we emit a MSSQL `MERGE ... OUTPUT` statement,
  # the native "insert-or-update" primitive, giving parity with the Postgres
  # `INSERT ... ON CONFLICT ... RETURNING` upsert.
  #
  # Known limitations vs Postgres: atomic expressions in the update clause
  # (`{:atomic, :upsert}`) are not supported (see `can?/2`); the update assigns
  # the incoming values directly.
  defp upsert_all_returning(source, resource, entries, options, action_select, repo, opts) do
    table = upsert_table(source, resource)
    prefix = opts[:prefix]
    qualified_table = if prefix, do: "[#{prefix}].[#{table}]", else: "[#{table}]"

    columns =
      entries
      |> Enum.flat_map(&Map.keys/1)
      |> Enum.uniq()

    keys = options[:upsert_keys] || Ash.Resource.Info.primary_key(resource)

    update_fields =
      (options[:upsert_fields] || columns -- keys)
      |> Enum.filter(&(&1 in columns))
      |> Enum.reject(&(&1 in keys))

    # OUTPUT what the action selects (parity with RETURNING); the full row when
    # there is no action_select. Filtering the schema's field list (rather than
    # mapping action_select directly) keeps unknown names out of the SQL.
    output_fields =
      case action_select do
        nil -> resource.__schema__(:fields)
        fields -> Enum.filter(resource.__schema__(:fields), &(&1 in fields))
      end

    output_columns =
      output_fields
      |> Enum.map(&resource.__schema__(:field_source, &1))
      |> Enum.uniq()

    {values_sql, params} = upsert_values(entries, columns, resource, repo)

    col_list = Enum.map_join(columns, ", ", &"[#{&1}]")

    on_clause = Enum.map_join(keys, " AND ", &"target.[#{&1}] = source.[#{&1}]")

    matched_clause =
      case update_fields do
        [] ->
          # Nothing to update on match: assign a key to itself so matched rows
          # still surface through OUTPUT.
          "WHEN MATCHED THEN UPDATE SET target.[#{Enum.at(keys, 0)}] = target.[#{Enum.at(keys, 0)}]"

        fields ->
          "WHEN MATCHED THEN UPDATE SET " <>
            Enum.map_join(fields, ", ", &"target.[#{&1}] = source.[#{&1}]")
      end

    output_clause = Enum.map_join(output_columns, ", ", &"INSERTED.[#{&1}]")

    sql = """
    MERGE INTO #{qualified_table} WITH (HOLDLOCK) AS target
    USING (VALUES #{values_sql}) AS source (#{col_list})
    ON (#{on_clause})
    #{matched_clause}
    WHEN NOT MATCHED BY TARGET THEN INSERT (#{col_list}) VALUES (#{Enum.map_join(columns, ", ", &"source.[#{&1}]")})
    OUTPUT #{output_clause};
    """

    %{columns: result_columns, rows: rows, num_rows: num_rows} = repo.query!(sql, params)

    records = Enum.map(rows, fn row -> repo.load(resource, {result_columns, row}) end)

    {num_rows, records}
  end

  defp upsert_table({table, _resource}, _fallback), do: table
  defp upsert_table(_source, resource), do: AshMssql.DataLayer.Info.table(resource)

  # `nil` action_select means the caller didn't restrict the selection (or the
  # capability isn't in play) and the full row is returned. Otherwise the
  # primary key is always retained, and so are `always_select?` attributes:
  # ash core's NotLoaded masking assumes the data layer loaded them, so
  # dropping them here would surface them as loaded `nil`s.
  defp action_select_with_required(nil, _resource), do: nil

  defp action_select_with_required(fields, resource) do
    fields
    |> Enum.concat(Ash.Resource.Info.primary_key(resource))
    |> Enum.concat(Ash.Resource.Info.always_selected_attribute_names(resource))
    |> Enum.uniq()
  end

  defp apply_action_select(query, nil), do: query

  defp apply_action_select(query, fields) do
    Ecto.Query.select(query, [row], struct(row, ^fields))
  end

  # Builds the MERGE VALUES clause (`(@1, @2), (@3, @4)`) plus the ordered,
  # adapter-dumped parameter list.
  defp upsert_values(entries, columns, resource, repo) do
    adapter = repo.__adapter__()

    {rows, params, _idx} =
      Enum.reduce(entries, {[], [], 1}, fn entry, {rows_acc, params_acc, idx} ->
        {placeholders, params_acc, idx} =
          Enum.reduce(columns, {[], params_acc, idx}, fn column, {ph, pacc, i} ->
            value = Map.get(entry, column)
            dumped = upsert_dump(adapter, resource, column, value)
            {["@#{i}" | ph], [dumped | pacc], i + 1}
          end)

        {["(#{placeholders |> Enum.reverse() |> Enum.join(", ")})" | rows_acc], params_acc, idx}
      end)

    {rows |> Enum.reverse() |> Enum.join(", "), Enum.reverse(params)}
  end

  defp upsert_dump(adapter, resource, column, value) do
    type = resource.__schema__(:type, column)

    case Ecto.Type.adapter_dump(adapter, type, value) do
      {:ok, dumped} -> dumped
      :error -> value
    end
  end

  # defp upsert_set(resource, changesets, options) do
  #   attributes_changing_anywhere =
  #     changesets |> Enum.flat_map(&Map.keys(&1.attributes)) |> Enum.uniq()

  #   update_defaults = update_defaults(resource)
  #   # We can't reference EXCLUDED if at least one of the changesets in the stream is not
  #   # changing the value (and we wouldn't want to even if we could as it would be unnecessary)

  #   upsert_fields =
  #     (options[:upsert_fields] || []) |> Enum.filter(&(&1 in attributes_changing_anywhere))

  #   fields_to_upsert =
  #     (upsert_fields ++ Keyword.keys(update_defaults)) --
  #       Keyword.keys(Enum.at(changesets, 0).atomics)

  #   Enum.map(fields_to_upsert, fn upsert_field ->
  #     # for safety, we check once more at the end that all values in
  #     # upsert_fields are names of attributes. This is because
  #     # below we use `literal/1` to bring them into the query
  #     if is_nil(resource.__schema__(:type, upsert_field)) do
  #       raise "Only attribute names can be used in upsert_fields"
  #     end

  #     case Keyword.fetch(update_defaults, upsert_field) do
  #       {:ok, default} ->
  #         if upsert_field in upsert_fields do
  #           {upsert_field,
  #            Ecto.Query.dynamic(
  #              [],
  #              fragment(
  #                "COALESCE(?, ?)",
  #                literal(^to_string(upsert_field)),
  #                ^default
  #              )
  #            )}
  #         else
  #           {upsert_field, default}
  #         end

  #       :error ->
  #         {upsert_field,
  #          Ecto.Query.dynamic(
  #            [],
  #            fragment("?", literal(^to_string(upsert_field)))
  #          )}
  #     end
  #   end)
  # end

  @impl true
  def create(resource, changeset) do
    changeset = %{
      changeset
      | data:
          Map.update!(
            changeset.data,
            :__meta__,
            &Map.put(&1, :source, table(resource, changeset))
          )
    }

    case bulk_create(resource, [changeset], %{
           single?: true,
           tenant: changeset.tenant,
           action_select: changeset.action_select,
           return_records?: true
         }) do
      {:ok, [result]} ->
        {:ok, result}

      {:error, error} ->
        {:error, error}
    end
  end

  defp handle_errors({:error, %Ecto.Changeset{errors: errors}}) do
    {:error, Enum.map(errors, &to_ash_error/1)}
  end

  defp to_ash_error({field, {message, vars}}) do
    Ash.Error.Changes.InvalidAttribute.exception(
      field: field,
      message: message,
      private_vars: vars
    )
  end

  defp ecto_changeset(record, changeset, type, table_error? \\ true) do
    filters =
      if changeset.action_type == :create do
        %{}
      else
        Map.get(changeset, :filters, %{})
      end

    filters =
      if changeset.action_type == :create do
        filters
      else
        changeset.resource
        |> Ash.Resource.Info.primary_key()
        |> Enum.reduce(filters, fn key, filters ->
          Map.put(filters, key, Map.get(record, key))
        end)
      end

    attributes =
      changeset.resource
      |> Ash.Resource.Info.attributes()
      |> Enum.map(& &1.name)

    attributes_to_change =
      Enum.reject(attributes, fn attribute ->
        Keyword.has_key?(changeset.atomics, attribute)
      end)

    ecto_changeset =
      record
      |> to_ecto()
      |> set_table(changeset, type, table_error?)
      |> Ecto.Changeset.change(Map.take(changeset.attributes, attributes_to_change))
      |> Map.update!(:filters, &Map.merge(&1, filters))
      |> add_configured_foreign_key_constraints(record.__struct__)
      |> add_unique_indexes(record.__struct__, changeset)
      |> add_exclusion_constraints(record.__struct__)

    case type do
      :create ->
        ecto_changeset
        |> add_my_foreign_key_constraints(record.__struct__)

      type when type in [:upsert, :update] ->
        ecto_changeset
        |> add_my_foreign_key_constraints(record.__struct__)
        |> add_related_foreign_key_constraints(record.__struct__)

      :delete ->
        ecto_changeset
        |> add_related_foreign_key_constraints(record.__struct__)
    end
  end

  defp handle_raised_error(
         %Ecto.StaleEntryError{changeset: %{data: %resource{}, filters: filters}},
         stacktrace,
         context,
         resource
       ) do
    handle_raised_error(
      Ash.Error.Changes.StaleRecord.exception(resource: resource, filters: filters),
      stacktrace,
      context,
      resource
    )
  end

  defp handle_raised_error(%Ecto.Query.CastError{} = e, stacktrace, context, resource) do
    handle_raised_error(
      Ash.Error.Query.InvalidFilterValue.exception(value: e.value, context: context),
      stacktrace,
      context,
      resource
    )
  end

  # MSSQL error 547: a statement conflicted with a FOREIGN KEY / REFERENCE
  # (or CHECK) constraint — e.g. inserting a row that references a missing parent.
  defp handle_raised_error(
         %Tds.Error{
           mssql: %{number: 547}
         },
         stacktrace,
         context,
         resource
       ) do
    handle_raised_error(
      Ash.Error.Changes.InvalidChanges.exception(
        fields: Ash.Resource.Info.primary_key(resource),
        message: "referenced something that does not exist"
      ),
      stacktrace,
      context,
      resource
    )
  end

  # MSSQL errors 2627 (PRIMARY KEY / UNIQUE constraint) and 2601 (unique index)
  # are duplicate-key violations. The constraint/index name is embedded in the
  # message text; migrations name unique indexes `<table>_<identity>_index`,
  # which `find_constraint_data/2` maps back to the offending identity.
  # sobelow_skip ["DOS.StringToAtom"]
  defp handle_raised_error(
         %Tds.Error{
           mssql: mssql
         },
         _stacktrace,
         _context,
         resource
       )
       when is_map(mssql) and (mssql.number == 2627 or mssql.number == 2601) do
    message_text = mssql[:msg_text] || ""

    index_name = extract_duplicate_key_name(message_text)

    %{fields: fields, message: message} =
      find_constraint_data(resource, index_name)

    message = message || "has already been taken"

    {:error,
     fields
     |> Enum.map(fn field ->
       Ash.Error.Changes.InvalidAttribute.exception(
         field: field,
         message: message
       )
     end)}
  end

  defp handle_raised_error(error, stacktrace, _ecto_changeset, _resource) do
    {:error, Ash.Error.to_ash_error(error, stacktrace)}
  end

  # Parse the constraint/index name out of an MSSQL duplicate-key message.
  # 2627: "Violation of UNIQUE KEY constraint 'name'. ..."
  #       "Violation of PRIMARY KEY constraint 'name'. ..."
  # 2601: "Cannot insert duplicate key row in object '...' with unique index 'name'. ..."
  # sobelow_skip ["DOS.StringToAtom"]
  defp extract_duplicate_key_name(message) do
    cond do
      Regex.match?(~r/PRIMARY KEY constraint/i, message) ->
        :PRIMARY

      match = Regex.run(~r/UNIQUE KEY constraint '([^']+)'/i, message, capture: :all_but_first) ->
        match |> Enum.at(0) |> String.to_atom()

      match = Regex.run(~r/unique index '([^']+)'/i, message, capture: :all_but_first) ->
        match |> Enum.at(0) |> String.to_atom()

      true ->
        :PRIMARY
    end
  end

  defp find_constraint_data(resource, :PRIMARY) do
    %{
      fields: Ash.Resource.Info.primary_key(resource),
      message: nil
    }
  end

  defp find_constraint_data(resource, index_name) do
    find_custom_index(resource, index_name) || find_identity(resource, index_name) ||
      %{fields: Ash.Resource.Info.primary_key(resource), message: nil}
  end

  defp find_custom_index(resource, searched_name) do
    table = AshMssql.DataLayer.Info.table(resource)

    resource
    |> AshMssql.DataLayer.Info.custom_indexes()
    |> Enum.find(fn custom_index ->
      name = AshMssql.CustomIndex.name(table, custom_index)
      name == searched_name
    end)
  end

  defp find_identity(resource, searched_index_name) do
    table = AshMssql.DataLayer.Info.table(resource)

    searched_identity_name =
      searched_index_name
      |> to_string()
      |> String.replace_prefix("#{table}_", "")
      |> String.replace_suffix("_index", "")

    identity =
      resource
      |> Ash.Resource.Info.identities()
      |> Enum.find(fn identity ->
        to_string(identity.name) == searched_identity_name
      end)

    case identity do
      nil -> nil
      identity -> %{fields: identity.keys, message: identity.message}
    end
  end

  defp set_table(record, changeset, operation, table_error?) do
    if AshMssql.DataLayer.Info.polymorphic?(record.__struct__) do
      table =
        changeset.context[:data_layer][:table] ||
          AshMssql.DataLayer.Info.table(record.__struct__)

      if table do
        Ecto.put_meta(record, source: table)
      else
        if table_error? do
          raise_table_error!(changeset.resource, operation)
        else
          record
        end
      end
    else
      record
    end
  end

  def from_ecto({:ok, result}), do: {:ok, from_ecto(result)}
  def from_ecto({:error, _} = other), do: other

  def from_ecto(nil), do: nil

  def from_ecto(value) when is_list(value) do
    Enum.map(value, &from_ecto/1)
  end

  def from_ecto(%resource{} = record) do
    if Spark.Dsl.is?(resource, Ash.Resource) do
      empty = struct(resource)

      resource
      |> Ash.Resource.Info.relationships()
      |> Enum.reduce(record, fn relationship, record ->
        case Map.get(record, relationship.name) do
          %Ecto.Association.NotLoaded{} ->
            Map.put(record, relationship.name, Map.get(empty, relationship.name))

          value ->
            Map.put(record, relationship.name, from_ecto(value))
        end
      end)
    else
      record
    end
  end

  def from_ecto(other), do: other

  def to_ecto(nil), do: nil

  def to_ecto(value) when is_list(value) do
    Enum.map(value, &to_ecto/1)
  end

  def to_ecto(%resource{} = record) do
    if Spark.Dsl.is?(resource, Ash.Resource) do
      resource
      |> Ash.Resource.Info.relationships()
      |> Enum.reduce(record, fn relationship, record ->
        value =
          case Map.get(record, relationship.name) do
            %Ash.NotLoaded{} ->
              %Ecto.Association.NotLoaded{
                __field__: relationship.name,
                __cardinality__: relationship.cardinality
              }

            value ->
              to_ecto(value)
          end

        Map.put(record, relationship.name, value)
      end)
    else
      record
    end
  end

  def to_ecto(other), do: other

  defp add_exclusion_constraints(changeset, resource) do
    resource
    |> AshMssql.DataLayer.Info.exclusion_constraint_names()
    |> Enum.reduce(changeset, fn constraint, changeset ->
      case constraint do
        {key, name} ->
          Ecto.Changeset.exclusion_constraint(changeset, key, name: name)

        {key, name, message} ->
          Ecto.Changeset.exclusion_constraint(changeset, key, name: name, message: message)
      end
    end)
  end

  defp add_related_foreign_key_constraints(changeset, resource) do
    # TODO: this doesn't guarantee us to get all of them, because if something is related to this
    # schema and there is no back-relation, then this won't catch it's foreign key constraints
    resource
    |> Ash.Resource.Info.relationships()
    |> Enum.map(& &1.destination)
    |> Enum.uniq()
    |> Enum.flat_map(fn related ->
      related
      |> Ash.Resource.Info.relationships()
      |> Enum.filter(&(&1.destination == resource))
      |> Enum.map(&Map.take(&1, [:source, :source_attribute, :destination_attribute, :name]))
    end)
    |> Enum.reduce(changeset, fn %{
                                   source: source,
                                   source_attribute: source_attribute,
                                   destination_attribute: destination_attribute,
                                   name: relationship_name
                                 },
                                 changeset ->
      case AshMssql.DataLayer.Info.reference(resource, relationship_name) do
        %{name: name} when not is_nil(name) ->
          Ecto.Changeset.foreign_key_constraint(changeset, destination_attribute,
            name: name,
            message: "would leave records behind"
          )

        _ ->
          Ecto.Changeset.foreign_key_constraint(changeset, destination_attribute,
            name: "#{AshMssql.DataLayer.Info.table(source)}_#{source_attribute}_fkey",
            message: "would leave records behind"
          )
      end
    end)
  end

  defp add_my_foreign_key_constraints(changeset, resource) do
    resource
    |> Ash.Resource.Info.relationships()
    |> Enum.reduce(changeset, &Ecto.Changeset.foreign_key_constraint(&2, &1.source_attribute))
  end

  defp add_configured_foreign_key_constraints(changeset, resource) do
    resource
    |> AshMssql.DataLayer.Info.foreign_key_names()
    |> case do
      {m, f, a} -> List.wrap(apply(m, f, [changeset | a]))
      value -> List.wrap(value)
    end
    |> Enum.reduce(changeset, fn
      {key, name}, changeset ->
        Ecto.Changeset.foreign_key_constraint(changeset, key, name: name)

      {key, name, message}, changeset ->
        Ecto.Changeset.foreign_key_constraint(changeset, key, name: name, message: message)
    end)
  end

  defp add_unique_indexes(changeset, resource, ash_changeset) do
    changeset =
      resource
      |> Ash.Resource.Info.identities()
      |> Enum.reduce(changeset, fn identity, changeset ->
        name =
          AshMssql.DataLayer.Info.identity_index_names(resource)[identity.name] ||
            "#{table(resource, ash_changeset)}_#{identity.name}_index"

        opts =
          if Map.get(identity, :message) do
            [name: name, message: identity.message]
          else
            [name: name]
          end

        Ecto.Changeset.unique_constraint(changeset, identity.keys, opts)
      end)

    changeset =
      resource
      |> AshMssql.DataLayer.Info.custom_indexes()
      |> Enum.reduce(changeset, fn index, changeset ->
        opts =
          if index.message do
            [name: index.name, message: index.message]
          else
            [name: index.name]
          end

        Ecto.Changeset.unique_constraint(changeset, index.fields, opts)
      end)

    names =
      resource
      |> AshMssql.DataLayer.Info.unique_index_names()
      |> case do
        {m, f, a} -> List.wrap(apply(m, f, [changeset | a]))
        value -> List.wrap(value)
      end

    names =
      case Ash.Resource.Info.primary_key(resource) do
        [] ->
          names

        fields ->
          if table = table(resource, ash_changeset) do
            [{fields, table <> "_pkey"} | names]
          else
            []
          end
      end

    Enum.reduce(names, changeset, fn
      {keys, name}, changeset ->
        Ecto.Changeset.unique_constraint(changeset, List.wrap(keys), name: name)

      {keys, name, message}, changeset ->
        Ecto.Changeset.unique_constraint(changeset, List.wrap(keys), name: name, message: message)
    end)
  end

  # @impl true
  @impl true
  def upsert(resource, changeset, keys) do
    keys = keys || Ash.Resource.Info.primary_key(resource)

    if changeset.atomics in [nil, []] do
      upsert_via_merge(resource, changeset, keys)
    else
      # Atomic expressions reference the *existing* row, which a MERGE VALUES
      # source cannot express. Use insert-then-atomic-update-on-conflict, reusing
      # the same atomic-update machinery as `update/2`.
      upsert_with_atomics(resource, changeset, keys)
    end
  end

  defp upsert_via_merge(resource, changeset, keys) do
    update_defaults = update_defaults(resource)

    # Fields to update on conflict: everything explicitly changing, plus
    # update_defaults (e.g. updated_at), minus attributes that were merely
    # defaulted (e.g. created_at, so it is preserved) and the conflict keys.
    explicitly_changing_attributes =
      changeset.attributes
      |> Map.keys()
      |> Enum.concat(Keyword.keys(update_defaults))
      |> Kernel.--(Map.get(changeset, :defaults, []))
      |> Kernel.--(keys)

    upsert_fields =
      changeset.context[:private][:upsert_fields] || explicitly_changing_attributes

    case bulk_create(resource, [changeset], %{
           single?: true,
           upsert?: true,
           tenant: changeset.tenant,
           upsert_keys: keys,
           upsert_fields: upsert_fields,
           action_select: changeset.action_select,
           return_records?: true
         }) do
      {:ok, [result]} ->
        {:ok, result}

      {:ok, []} ->
        {:ok, nil}

      {:error, error} ->
        {:error, error}
    end
  end

  # Upserts with atomics run inside an Ash transaction, so we cannot rely on
  # catching a unique-violation and continuing (a failed statement dooms the
  # transaction). Instead we check for the existing row by key and branch to an
  # atomic UPDATE or an INSERT, relying on the surrounding transaction for
  # isolation. (Non-atomic upserts use a single atomic MERGE; this SELECT-then-
  # write path is only for the atomic case and is not hardened against a
  # concurrent insert of the same key outside a serializable transaction.)
  defp upsert_with_atomics(resource, changeset, keys) do
    repo = dynamic_repo(resource, changeset)
    key_values = Enum.map(keys, fn key -> {key, Map.get(changeset.attributes, key)} end)

    existing =
      from(row in resource, as: ^0)
      |> Ecto.Query.where(^key_values)
      |> repo.one()

    if existing do
      atomic_conflict_update(resource, changeset, keys, repo)
    else
      source = resolve_source(resource, changeset)

      opts =
        case changeset.context[:data_layer][:schema] do
          nil -> repo_opts(nil, changeset.tenant, resource)
          schema -> Keyword.put(repo_opts(nil, changeset.tenant, resource), :prefix, schema)
        end

      action_select = action_select_with_required(changeset.action_select, resource)

      case insert_all_returning(
             source,
             [changeset.attributes],
             repo,
             resource,
             action_select,
             opts
           ) do
        {_count, [record]} -> {:ok, record}
        {_count, _} -> {:ok, nil}
      end
    end
  end

  # Apply the atomics (and any other upsert fields) as an UPDATE to the
  # conflicting row, then reload it. Mirrors `update/2`'s atomic handling.
  defp atomic_conflict_update(resource, changeset, keys, repo) do
    ecto_changeset = ecto_changeset(changeset.data, changeset, :create, false)
    key_values = Enum.map(keys, fn key -> {key, Map.get(changeset.attributes, key)} end)
    atomic_keys = Keyword.keys(changeset.atomics)
    update_defaults = update_defaults(resource)

    upsert_fields =
      (changeset.context[:private][:upsert_fields] ||
         Map.keys(changeset.attributes) ++ Keyword.keys(update_defaults))
      |> Kernel.--(Map.get(changeset, :defaults, []))
      |> Kernel.--(keys)
      |> Kernel.--(atomic_keys)

    changes = Map.take(ecto_changeset.changes, upsert_fields)

    query =
      from(row in resource, as: ^0)
      |> AshSql.Bindings.default_bindings(resource, AshMssql.SqlImplementation, changeset.context)
      |> Ecto.Query.where(^key_values)

    case AshSql.Atomics.query_with_atomics(
           resource,
           query,
           changeset.filter,
           changeset.atomics,
           changes,
           []
         ) do
      {:ok, query} ->
        repo.update_all(query, [], repo_opts(nil, changeset.tenant, resource))

        # Atomics are computed in the database, so they must be part of the
        # reload even when the action's select doesn't ask for them.
        reload_select =
          case action_select_with_required(changeset.action_select, resource) do
            nil -> nil
            fields -> Enum.uniq(fields ++ atomic_keys)
          end

        result =
          from(row in resource, as: ^0)
          |> Ecto.Query.where(^key_values)
          |> apply_action_select(reload_select)
          |> repo.all()
          |> List.first()

        {:ok, result}

      {:error, error} ->
        {:error, error}
    end
  end

  # defp conflict_target(resource, keys) do
  #   if Ash.Resource.Info.base_filter(resource) do
  #     base_filter_sql =
  #       AshMssql.DataLayer.Info.base_filter_sql(resource) ||
  #         raise """
  #         Cannot use upserts with resources that have a base_filter without also adding `base_filter_sql` in the mssql
  #         section.
  #         """

  #     sources =
  #       Enum.map(keys, fn key ->
  #         ~s("#{Ash.Resource.Info.attribute(resource, key).source || key}")
  #       end)

  #     {:unsafe_fragment, "(" <> Enum.join(sources, ", ") <> ") WHERE (#{base_filter_sql})"}
  #   else
  #     keys
  #   end
  # end

  defp update_defaults(resource) do
    attributes =
      resource
      |> Ash.Resource.Info.attributes()
      |> Enum.reject(&is_nil(&1.update_default))

    attributes
    |> static_defaults()
    |> Enum.concat(lazy_matching_defaults(attributes))
    |> Enum.concat(lazy_non_matching_defaults(attributes))
  end

  defp static_defaults(attributes) do
    attributes
    |> Enum.reject(&get_default_fun(&1))
    |> Enum.map(&{&1.name, &1.update_default})
  end

  defp lazy_non_matching_defaults(attributes) do
    attributes
    |> Enum.filter(&(!&1.match_other_defaults? && get_default_fun(&1)))
    |> Enum.map(fn attribute ->
      default_value =
        case attribute.update_default do
          function when is_function(function) ->
            function.()

          {m, f, a} when is_atom(m) and is_atom(f) and is_list(a) ->
            apply(m, f, a)
        end

      {attribute.name, default_value}
    end)
  end

  defp lazy_matching_defaults(attributes) do
    attributes
    |> Enum.filter(&(&1.match_other_defaults? && get_default_fun(&1)))
    |> Enum.group_by(& &1.update_default)
    |> Enum.flat_map(fn {default_fun, attributes} ->
      default_value =
        case default_fun do
          function when is_function(function) ->
            function.()

          {m, f, a} when is_atom(m) and is_atom(f) and is_list(a) ->
            apply(m, f, a)
        end

      Enum.map(attributes, &{&1.name, default_value})
    end)
  end

  defp get_default_fun(attribute) do
    if is_function(attribute.update_default) or match?({_, _, _}, attribute.update_default) do
      attribute.update_default
    end
  end

  @impl true
  def update(resource, changeset) do
    ecto_changeset =
      changeset.data
      |> Map.update!(:__meta__, &Map.put(&1, :source, table(resource, changeset)))
      |> ecto_changeset(changeset, :update)

    try do
      query = from(row in resource, as: ^0)

      # Atomics are computed in the database, so their values must come from
      # the reload. The action_select fields only fill in whatever the
      # changeset doesn't already carry — attributes written by this changeset
      # stay authoritative, so a concurrent writer (with `transaction?: false`)
      # can't leak its values into our result.
      reloaded_action_select =
        changeset.action_select
        |> List.wrap()
        |> Enum.concat(Ash.Resource.Info.always_selected_attribute_names(resource))
        |> Enum.uniq()
        |> Kernel.--(Keyword.keys(changeset.atomics) ++ Map.keys(changeset.attributes))

      select =
        Enum.uniq(
          Keyword.keys(changeset.atomics) ++
            reloaded_action_select ++ Ash.Resource.Info.primary_key(resource)
        )

      query =
        query
        |> AshSql.Bindings.default_bindings(
          resource,
          AshMssql.SqlImplementation,
          changeset.context
        )
        # |> Ecto.Query.select(^select)
        |> pkey_filter(changeset.data)

      case AshSql.Atomics.query_with_atomics(
             resource,
             query,
             changeset.filter,
             changeset.atomics,
             ecto_changeset.changes,
             []
           ) do
        {:ok, query} ->
          repo_opts = repo_opts(changeset.timeout, changeset.tenant, changeset.resource)

          # repo_opts =
          #  Keyword.put(repo_opts, :returning, Keyword.keys(changeset.atomics))

          repo = dynamic_repo(resource, changeset)

          {count, nil} =
            repo.update_all(query, [], repo_opts)

          result =
            from(row in resource, as: ^0, select: ^select)
            |> pkey_filter(changeset.data)
            |> repo.all(Keyword.take(repo_opts, [:prefix, :timeout]))

          case {count, result} do
            {0, []} ->
              {:error,
               Ash.Error.Changes.StaleRecord.exception(
                 resource: resource,
                 filters: changeset.filter
               )}

            {1, [result]} ->
              record =
                changeset.data
                |> Map.merge(changeset.attributes)
                |> Map.merge(
                  Map.take(result, Keyword.keys(changeset.atomics) ++ reloaded_action_select)
                )

              {:ok, record}
          end

        {:error, error} ->
          {:error, error}
      end
    rescue
      e ->
        handle_raised_error(e, __STACKTRACE__, ecto_changeset, resource)
    end
  end

  defp pkey_filter(query, %resource{} = record) do
    pkey =
      record
      |> Map.take(Ash.Resource.Info.primary_key(resource))
      |> Map.to_list()

    Ecto.Query.where(query, ^pkey)
  end

  @impl true
  def destroy(resource, %{data: record} = changeset) do
    ecto_changeset = ecto_changeset(record, changeset, :delete)

    try do
      ecto_changeset
      |> dynamic_repo(resource, changeset).delete(
        repo_opts(changeset.timeout, changeset.resource)
      )
      |> from_ecto()
      |> case do
        {:ok, _record} ->
          :ok

        {:error, error} ->
          handle_errors({:error, error})
      end
    rescue
      e ->
        handle_raised_error(e, __STACKTRACE__, ecto_changeset, resource)
    end
  end

  @impl true
  def sort(query, sort, _resource) do
    {:ok, Map.update!(query, :__ash_bindings__, &Map.put(&1, :sort, sort))}
  end

  @impl true
  def select(query, select, resource) do
    query = AshSql.Bindings.default_bindings(query, resource, AshMssql.SqlImplementation)

    {:ok,
     from(row in query,
       select: struct(row, ^Enum.uniq(select))
     )}
  end

  @doc false
  def unwrap_one([thing]), do: thing
  def unwrap_one([]), do: nil
  def unwrap_one(other), do: other

  @impl true
  def filter(query, filter, _resource, opts \\ []) do
    query
    |> AshSql.Join.join_all_relationships(filter, opts)
    |> case do
      {:ok, query} ->
        {:ok, AshSql.Filter.add_filter_expression(query, filter)}

      {:error, error} ->
        {:error, error}
    end
  end

  @impl true
  def add_calculations(query, calculations, resource) do
    AshSql.Calculation.add_calculations(query, calculations, resource, 0, true)
  end

  @doc false
  def get_binding(resource, path, query, type, name_match \\ nil)

  def get_binding(resource, path, %{__ash_bindings__: _} = query, type, name_match) do
    types = List.wrap(type)

    Enum.find_value(query.__ash_bindings__.bindings, fn
      {binding, %{path: candidate_path, type: binding_type} = data} ->
        if binding_type in types do
          if name_match do
            if data[:name] == name_match do
              if Ash.SatSolver.synonymous_relationship_paths?(resource, candidate_path, path) do
                binding
              end
            end
          else
            if Ash.SatSolver.synonymous_relationship_paths?(resource, candidate_path, path) do
              binding
            else
              false
            end
          end
        end

      _ ->
        nil
    end)
  end

  def get_binding(_, _, _, _, _), do: nil

  @doc false
  def add_binding(query, data, additional_bindings \\ 0) do
    current = query.__ash_bindings__.current
    bindings = query.__ash_bindings__.bindings

    new_ash_bindings = %{
      query.__ash_bindings__
      | bindings: Map.put(bindings, current, data),
        current: current + 1 + additional_bindings
    }

    %{query | __ash_bindings__: new_ash_bindings}
  end

  def add_known_binding(query, data, known_binding) do
    bindings = query.__ash_bindings__.bindings

    new_ash_bindings = %{
      query.__ash_bindings__
      | bindings: Map.put(bindings, known_binding, data)
    }

    %{query | __ash_bindings__: new_ash_bindings}
  end

  @impl true
  def transaction(resource, func, timeout \\ nil, reason \\ %{type: :custom, metadata: %{}}) do
    # An explicit repo in the data-layer context (e.g. a dynamically selected
    # repo) takes precedence, matching ash_postgres.
    repo =
      case reason[:data_layer_context] do
        %{repo: repo} when not is_nil(repo) ->
          repo

        _ ->
          AshMssql.DataLayer.Info.repo(resource)
      end

    if timeout do
      repo.transaction(func, timeout: timeout)
    else
      repo.transaction(func)
    end
  end

  @impl true
  def in_transaction?(resource) do
    AshMssql.DataLayer.Info.repo(resource).in_transaction?()
  end

  @impl true
  def rollback(resource, term) do
    AshMssql.DataLayer.Info.repo(resource).rollback(term)
  end

  defp table(resource, changeset) do
    changeset.context[:data_layer][:table] || AshMssql.DataLayer.Info.table(resource)
  end

  defp raise_table_error!(resource, operation) do
    if AshMssql.DataLayer.Info.polymorphic?(resource) do
      raise """
      Could not determine table for #{operation} on #{inspect(resource)}.

      Polymorphic resources require that the `data_layer[:table]` context is provided.
      See the guide on polymorphic resources for more information.
      """
    else
      raise """
      Could not determine table for #{operation} on #{inspect(resource)}.
      """
    end
  end

  # `type` is `:read` or `:mutate`; it selects the read/replica or mutate repo
  # when the resource configures its `repo` as a function. An explicit repo in
  # the data-layer context always wins.
  defp dynamic_repo(resource, subject, type \\ :mutate)

  defp dynamic_repo(resource, %{__ash_bindings__: %{context: %{data_layer: %{repo: repo}}}}, type) do
    repo || AshMssql.DataLayer.Info.repo(resource, type)
  end

  defp dynamic_repo(resource, %{context: %{data_layer: %{repo: repo}}}, type) do
    repo || AshMssql.DataLayer.Info.repo(resource, type)
  end

  defp dynamic_repo(resource, _, type) do
    AshMssql.DataLayer.Info.repo(resource, type)
  end

  defp resolve_source(resource, changeset) do
    if table = changeset.context[:data_layer][:table] do
      {table, resource}
    else
      resource
    end
  end
end
