defmodule AshMssql.TestRepo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_mssql.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:uuid_v7_posts, primary_key: false) do
      add :title, :string
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:uuid_v7_posts)
  end
end