defmodule AshMssql.TestRepo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_mssql.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'posts') AND c.name = N'updated_at'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [posts] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute(
      "ALTER TABLE [posts] ADD CONSTRAINT [DF__posts_updated_at] DEFAULT (SYSUTCDATETIME()) FOR [updated_at];"
    )

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'posts') AND c.name = N'created_at'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [posts] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute(
      "ALTER TABLE [posts] ADD CONSTRAINT [DF__posts_created_at] DEFAULT (SYSUTCDATETIME()) FOR [created_at];"
    )

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'comments') AND c.name = N'created_at'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [comments] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute(
      "ALTER TABLE [comments] ADD CONSTRAINT [DF__comments_created_at] DEFAULT (SYSUTCDATETIME()) FOR [created_at];"
    )

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'post_views') AND c.name = N'time'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [post_views] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute(
      "ALTER TABLE [post_views] ADD CONSTRAINT [DF__post_views_time] DEFAULT (SYSUTCDATETIME()) FOR [time];"
    )
  end

  def down do
    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'post_views') AND c.name = N'time'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [post_views] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'comments') AND c.name = N'created_at'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [comments] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'posts') AND c.name = N'created_at'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [posts] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'posts') AND c.name = N'updated_at'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [posts] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)
  end
end