defmodule AshMssql.TestRepo.Migrations.CiStringCollationAndPostEmail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_mssql.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      modify :category, :"NVARCHAR(255) COLLATE SQL_Latin1_General_CP1_CI_AS"
      add :email, :string
    end
  end

  def down do
    alter table(:posts) do
      remove :email
      modify :category, :string
    end
  end
end