defmodule AshMssql.TestRepo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_mssql.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'orgs') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [orgs] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("ALTER TABLE [orgs] ADD CONSTRAINT [DF__orgs_id] DEFAULT (NEWID()) FOR [id];")

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'users') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [users] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("ALTER TABLE [users] ADD CONSTRAINT [DF__users_id] DEFAULT (NEWID()) FOR [id];")

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'accounts') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [accounts] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("ALTER TABLE [accounts] ADD CONSTRAINT [DF__accounts_id] DEFAULT (NEWID()) FOR [id];")

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'authors') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [authors] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("ALTER TABLE [authors] ADD CONSTRAINT [DF__authors_id] DEFAULT (NEWID()) FOR [id];")

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'posts') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [posts] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("ALTER TABLE [posts] ADD CONSTRAINT [DF__posts_id] DEFAULT (NEWID()) FOR [id];")

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'comments') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [comments] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("ALTER TABLE [comments] ADD CONSTRAINT [DF__comments_id] DEFAULT (NEWID()) FOR [id];")

    drop constraint(:comment_ratings, "comment_ratings_resource_id_fkey")

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'comment_ratings') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [comment_ratings] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute(
      "ALTER TABLE [comment_ratings] ADD CONSTRAINT [DF__comment_ratings_id] DEFAULT (NEWID()) FOR [id];"
    )

    alter table(:comment_ratings) do
      modify :resource_id,
             references(:comments,
               column: :id,
               name: "comment_ratings_resource_id_fkey",
               type: :uuid
             )
    end

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'managers') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [managers] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("ALTER TABLE [managers] ADD CONSTRAINT [DF__managers_id] DEFAULT (NEWID()) FOR [id];")

    drop constraint(:post_ratings, "post_ratings_resource_id_fkey")

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'post_ratings') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [post_ratings] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute(
      "ALTER TABLE [post_ratings] ADD CONSTRAINT [DF__post_ratings_id] DEFAULT (NEWID()) FOR [id];"
    )

    alter table(:post_ratings) do
      modify :resource_id,
             references(:posts, column: :id, name: "post_ratings_resource_id_fkey", type: :uuid)
    end

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'profile') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [profile] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("ALTER TABLE [profile] ADD CONSTRAINT [DF__profile_id] DEFAULT (NEWID()) FOR [id];")

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'uuid_v7_posts') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [uuid_v7_posts] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute(
      "ALTER TABLE [uuid_v7_posts] ADD CONSTRAINT [DF__uuid_v7_posts_id] DEFAULT (CONVERT(uniqueidentifier, STUFF(STUFF(LOWER(CONVERT(char(36), NEWID())), 1, 13, STUFF(CONVERT(varchar(12), CONVERT(binary(6), DATEDIFF_BIG(millisecond, '1970-01-01', SYSUTCDATETIME())), 2), 9, 0, '-')), 15, 1, '7'))) FOR [id];"
    )
  end

  def down do
    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'uuid_v7_posts') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [uuid_v7_posts] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'profile') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [profile] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    drop constraint(:post_ratings, "post_ratings_resource_id_fkey")

    alter table(:post_ratings) do
      modify :resource_id,
             references(:posts, column: :id, name: "post_ratings_resource_id_fkey", type: :uuid)
    end

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'post_ratings') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [post_ratings] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'managers') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [managers] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    drop constraint(:comment_ratings, "comment_ratings_resource_id_fkey")

    alter table(:comment_ratings) do
      modify :resource_id,
             references(:comments,
               column: :id,
               name: "comment_ratings_resource_id_fkey",
               type: :uuid
             )
    end

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'comment_ratings') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [comment_ratings] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'comments') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [comments] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'posts') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [posts] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'authors') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [authors] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'accounts') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [accounts] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'users') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [users] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)

    execute("""
    DECLARE @df sysname, @sql nvarchar(max); SELECT @df = d.name FROM sys.default_constraints d JOIN sys.columns c ON c.object_id = d.parent_object_id AND c.column_id = d.parent_column_id WHERE d.parent_object_id = OBJECT_ID(N'orgs') AND c.name = N'id'; IF @df IS NOT NULL BEGIN SET @sql = N'ALTER TABLE [orgs] DROP CONSTRAINT ' + QUOTENAME(@df); EXEC(@sql); END;
    """)
  end
end