defmodule AshMssql.TestRepo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_mssql.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:accounts) do
      add :db_v4, :uuid, default: fragment("NEWID()")
    end

    alter table(:uuid_v7_posts) do
      add :db_v7, :uuid,
        default:
          fragment(
            "CONVERT(uniqueidentifier, STUFF(STUFF(LOWER(CONVERT(char(36), NEWID())), 1, 13, STUFF(CONVERT(varchar(12), CONVERT(binary(6), DATEDIFF_BIG(millisecond, '1970-01-01', SYSUTCDATETIME())), 2), 9, 0, '-')), 15, 1, '7'))"
          )
    end
  end

  def down do
    alter table(:uuid_v7_posts) do
      remove :db_v7
    end

    alter table(:accounts) do
      remove :db_v4
    end
  end
end