name: CI
on:
  push:
    tags:
      - "v*"
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ash-ci:
    strategy:
      fail-fast: false
      matrix:
        mssql-version: ["2022-latest", "2025-latest"]
    uses: ./.github/workflows/ash-ci.yml
    with:
      mssql: true
      mssql-version: ${{matrix.mssql-version}}
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
